// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/example": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/api": {
    params: {};
  };
  "/api/log-error": {
    params: {};
  };
  "/about/register": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/example" | "/register" | "/login" | "/logout" | "/profile" | "/home" | "/api" | "/api/log-error" | "/about/register" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "./routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "./routes/example.tsx": {
    id: "routes/example";
    page: "/example";
  };
  "./routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "./routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "./routes/api/api.tsx": {
    id: "routes/api/api";
    page: "/api" | "/api/log-error";
  };
  "./routes/api/errors-log.tsx": {
    id: "routes/api/errors-log";
    page: "/api/log-error";
  };
  "./routes/_about.register.tsx": {
    id: "routes/_about.register";
    page: "/about/register";
  };
  "./routes/bots/[.]well-known.tsx": {
    id: "routes/bots/[.]well-known";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
};